package org.launchcode.attendtrac.Models;
import org.springframework.format.annotation.DateTimeFormat;
import sun.security.x509.AttributeNameEnumeration;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

//entity tells spring boot you want to store this in a table and every field
@Entity
public class Meeting {

    //this is generated by the data layer and is a primary key
    @Id
    @GeneratedValue
    private int id;

    //validation not empty
    @NotNull
    private String date;

    @NotNull
    //the entry must be within this range
    @Size(min=1, max=20)
    private String type;

    //there can be many meetings to each attendee
    @ManyToMany
    private List<Attendee> attendees;

    //all persistent classes should have a default constructor that Thymeleaf uses
    public Meeting(){}

    public Meeting(int id, String date, String type) {
        this.id = id;
        this.date = date;
        this.type = type;

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public List<Attendee> getAttendees() {
        return attendees;
    }

    public void addAttendee(Attendee theAttendee) {
        attendees.add(theAttendee);}

    }